# -*- coding: utf-8 -*-
# Copyright (c) Facebook, Inc. and its affiliates. All Rights Reserved
from detectron2.config import CfgNode as CN


def add_detr_config(cfg):
    """
    Add config for DETR.
    """
    cfg.MODEL.DETR = CN()
    cfg.MODEL.DETR.NUM_CLASSES = 80

    # For Segmentation
    cfg.MODEL.DETR.FROZEN_WEIGHTS = ''

    # LOSS
    cfg.MODEL.DETR.GIOU_WEIGHT = 2.0
    cfg.MODEL.DETR.L1_WEIGHT = 5.0
    cfg.MODEL.DETR.DEEP_SUPERVISION = True
    cfg.MODEL.DETR.NO_OBJECT_WEIGHT = 0.1

    # TRANSFORMER
    cfg.MODEL.DETR.NHEADS = 8
    cfg.MODEL.DETR.DROPOUT = 0.1
    cfg.MODEL.DETR.DIM_FEEDFORWARD = 2048
    cfg.MODEL.DETR.ENC_LAYERS = 6
    cfg.MODEL.DETR.DEC_LAYERS = 6
    cfg.MODEL.DETR.PRE_NORM = False

    cfg.MODEL.DETR.HIDDEN_DIM = 256
    cfg.MODEL.DETR.NUM_OBJECT_QUERIES = 100

    cfg.SOLVER.OPTIMIZER = "ADAMW"
    cfg.SOLVER.BACKBONE_MULTIPLIER = 0.1



def add_deformable_config(cfg):
    """
    Add config for DQRF
    """
    cfg.MODEL.DF_DETR  = CN()
    cfg.MODEL.DF_DETR.NUM_CLASSES = 15
    cfg.MODEL.DF_DETR.NUM_QUERIES = 80
    cfg.MODEL.DF_DETR.FOCAL_ALPHA = 0.25
    cfg.MODEL.DF_DETR.GAMMA = 2.0

    #TRANSFORMER
    cfg.MODEL.DF_DETR.HIDDEN_DIM = 256
    cfg.MODEL.DF_DETR.NHEAD = 8
    cfg.MODEL.DF_DETR.NUM_DECODER_LAYERS = 6
    cfg.MODEL.DF_DETR.NUM_ENCODER_LAYERS = 6
    cfg.MODEL.DF_DETR.DIM_FEEDFORWARD = 1024
    cfg.MODEL.DF_DETR.ACTIVATION = "relu"
    cfg.MODEL.DF_DETR.DROPOUT = 0.1
    cfg.MODEL.DF_DETR.NUM_FEATURE_LEVELS = 4
    cfg.MODEL.DF_DETR.ENC_SAMPLING_POINTS = 4
    cfg.MODEL.DF_DETR.DEC_SAMPLING_POINTS = 4
    cfg.MODEL.DF_DETR.POS_ENCODING = 'sine'

    #LOSS
    cfg.MODEL.DF_DETR.AUX_LOSS = True
    cfg.MODEL.DF_DETR.V_MATCH = 3
    cfg.MODEL.DF_DETR.COST_CLASS = 2
    cfg.MODEL.DF_DETR.COST_BBOX = 5
    cfg.MODEL.DF_DETR.COST_GIOU = 2

    #DQRF
    cfg.MODEL.DF_DETR.DENSE_QUERY = False
    cfg.MODEL.DF_DETR.RECTIFIED_ATTENTION = False
    cfg.MODEL.DF_DETR.IGNORE_IOU_THRESHOLD = 0.5

    #SOLVER
    cfg.SOLVER.OPTIMIZER = "ADAMW"
    cfg.SOLVER.BACKBONE_MULTIPLIER = 0.1
    cfg.SOLVER.SAMPLE_MULTIPLIER = 0.1
    cfg.SOLVER.CENTER_MULTPLIER = 0.1
    cfg.SOLVER.WEIGHT_MULTIPLIER = 1.0
